# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6f31a5f4365a2dc9b912a56d94a70f0a7e9a948cec671f941460ae59fc2ca4a6f2c2233605ea5866b40e2cfb8b97df03aafcbdd98fe6e645ca7c7b27089d925

test:
  secret_key_base: b590353ade0d5255bb8d5803e9910a25994912a446306fbe0936db940258e45fb490cf4967b75d2ccfb01217a673f2d7ae8c85a5f929448892c7f1722e28c368

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
